# =========================================================
# APPLICATION
# =========================================================

spring.application.name=online-banking

server.port=8080

server.shutdown=graceful


# =========================================================
# DATABASE - LOCAL POSTGRESQL
# =========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/online_banking

spring.datasource.username=postgres

spring.datasource.password=12345678

spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================================
# HIKARI CONNECTION POOL
# =========================================================

spring.datasource.hikari.pool-name=OnlineBankingHikariPool

spring.datasource.hikari.maximum-pool-size=10

spring.datasource.hikari.minimum-idle=2

spring.datasource.hikari.connection-timeout=30000

spring.datasource.hikari.idle-timeout=600000

spring.datasource.hikari.max-lifetime=1800000


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=true

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# JWT
# =========================================================

jwt.secret=my-online-banking-secret-key-must-be-long-enough-123456

jwt.expiration=86400000


# =========================================================
# CORS
# =========================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cbank8018@gmail.com
spring.mail.password=uvyxhmfsprfugvsm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

